#include "main.h"

static struct talent_info {
	const char*			id;
	const char*			name;
} talent_data[] = {{"Adaptible", "Адаптивный"},
{"InnerPeace", "Внутренее спокойствие"},
{"PsychicPower", "Психическая сила"},
{"TrueGrit", "Истинное мужество"},
{"HardToCatch", "Тяжело поймать"},
{"HuntingInstinct", "Охотничий инстинкт"},
{"Unbreakable", "Неуязвимый"},
{"Sneaky", "Скрытный"},
//
{"PathOfHealing", "Путь целителя"},
{"PathOfShiftingShapes", "Путь оборотня"},
{"PathOfSight", "Путь прорицателя"},
{"PathOfBlade", "Путь меча"},
{"PathOfShield", "Путь щита"},
{"PathOfArrow", "Путь стрелы"},
{"PathOfBeast", "Путь бестии"},
{"PathOfForest", "Путь леса"},
{"PathOfHymn", "Путь гимна"},
{"PathOfSong", "Путь пения"},
{"PathOfWarcry", "Путь боевого клича"},
{"PathOfGold", "Путь золота"},
{"PathOfLies", "Путь лжи"},
{"PathOfManyThings", "Путь многих вещей"},
{"PathOfCompanion", "Путь компаньенов"},
{"PathOfKnight", "Путь рыцаря"},
{"PathOfPlains", "Путь равнин"},
{"PathOfFace", "Путь многих лиц"},
{"PathOfKiller", "Путь убийцы"},
{"PathOfPoison", "Путь яда"},
{"PathOfBlood", "Путь крови"},
{"PathOfDeath", "Путь смерти"},
{"PathOfSigns", "Путь знаков"},
{"PathOfStone", "Путь камня"},
//
{"Ambidexterous", "Владеющий двумя руками"},
{"AxeFighter", "Боец с топором"},
{"Berserker", "Берсеркер"},
{"Bowyer", "Лукодел"},
{"Brawler", "Драчун"},
{"Builder", "Строитель"},
{"Chef", "Повар"},
{"ColdBlooded", "Хладнокровный"},
{"Defender", "Защитник"},
{"Dragonslayer", "Убийца Драконов"},
{"Executioner", "Палач"},
{"FastFootwork", "БЫстрая работа ног"},
{"FastShooter", "Быстрый стрелок"},
{"Fearless", "Безстрашный"},
{"FirmGrip", "Крепкая хватка"},
{"Fisher", "Рыбак"},
{"HammerFighter", "Боец с молотом"},
{"Herbalist", "Травник"},
{"HorsebackFighter", "Конный боец"},
{"Incorruptible", "Неподкупный"},
{"KnifeFighter", "Боец на ножах"},
{"LightingFast", "Скоростной"},
{"Lockpicker", "Взломщик"},
{"Lucky", "Удачливый"},
{"MasterOfTheHunt", "Мастер охоты"},
{"MeleeCharge", "Атака с наскока"},
{"PackRat", "Мастер упаковки"},
{"PathFinder", "Путеводитель"},
{"Poisoner", "Мастер ядов"},
{"QuarterMaster", "Мастер лагерей"},
{"QuickDraw", "Быстрое выхватывание"},
{"Sailor", "Моряк"},
{"Sharpshooter", "Меткий стрелок"},
{"SharpTongue", "Острый язык"},
{"ShieldFighter", "Боец с щитом"},
{"SixthSense", "Шестое чувство"},
{"Smith", "Кузнец"},
{"SpearFighter", "Боец с копьем"},
{"SteadyFeet", "Устойчивые ноги"},
{"SwordFighter", "Боец на мечах"},
{"Tailor", "Портной"},
{"Tanner", "Дубильщик"},
{"Threatening", "Угрожающий"},
{"ThrowingArm", "Наметанная рука"},
{"Wanderer", "Путишественник"},
};
getstr_enum(talent);
assert_enum(talent, Wanderer);