#include "main.h"

static struct talent_info {
	const char*		id;
	const char*		name;
	variant			type;
} talent_data[] = {{"Adaptible", "Адаптивный", Human},
{"InnerPeace", "Внутренее спокойствие", Elf},
{"PsychicPower", "Психическая сила", HalfElf},
{"TrueGrit", "Истинное мужество", Dwarf},
{"HardToCatch", "Тяжело поймать", Halfling},
{"HuntingInstinct", "Охотничий инстинкт", Wolfkin},
{"Unbreakable", "Неуязвимый", Orc},
{"Sneaky", "Скрытный", Goblin},
//
{"PathOfHealing", "Путь целителя", Druid},
{"PathOfShiftingShapes", "Путь оборотня", Druid},
{"PathOfSight", "Путь прорицателя", Druid},
{"PathOfBlade", "Путь клинка", Fighter},
{"PathOfShield", "Путь щита", Fighter},
{"PathOfArrow", "Путь стрелы", Hunter},
{"PathOfBeast", "Путь бестии", Hunter},
{"PathOfForest", "Путь леса", Hunter},
{"PathOfHymn", "Путь гимна", Minstrel},
{"PathOfSong", "Путь пения", Minstrel},
{"PathOfWarcry", "Путь боевого клича", Minstrel},
{"PathOfGold", "Путь золота", Peddler},
{"PathOfLies", "Путь лжи", Peddler},
{"PathOfManyThings", "Путь многих вещей", Peddler},
{"PathOfCompanion", "Путь компаньенов", Rider},
{"PathOfKnight", "Путь рыцаря", Rider},
{"PathOfPlains", "Путь равнин", Rider},
{"PathOfFace", "Путь многих лиц", Rogue},
{"PathOfKiller", "Путь убийцы", Rogue},
{"PathOfPoison", "Путь яда", Rogue},
{"PathOfBlood", "Путь крови", Sorcerer},
{"PathOfDeath", "Путь смерти", Sorcerer},
{"PathOfSigns", "Путь знаков", Sorcerer},
{"PathOfStone", "Путь камня", Sorcerer},
//
{"Ambidexterous", "Владеющий двумя руками"},
{"AxeFighter", "Боец на топорах"},
{"Berserker", "Берсеркер"},
{"Bowyer", "Лукодел"},
{"Brawler", "Драчун"},
{"Builder", "Строитель"},
{"Chef", "Повар"},
{"ColdBlooded", "Хладнокровный"},
{"Defender", "Защитник"},
{"Dragonslayer", "Убийца Драконов"},
{"Executioner", "Палач"},
{"FastFootwork", "Быстрая работа ног"},
{"FastShooter", "Быстрый стрелок"},
{"Fearless", "Безстрашный"},
{"FirmGrip", "Крепкая хватка"},
{"Fisher", "Рыбак"},
{"HammerFighter", "Боец с молотом"},
{"Herbalist", "Травник"},
{"HorsebackFighter", "Конный боец"},
{"Incorruptible", "Неподкупный"},
{"KnifeFighter", "Боец на ножах"},
{"LightingFast", "Скоростной"},
{"Lockpicker", "Взломщик"},
{"Lucky", "Удачливый"},
{"MasterOfTheHunt", "Мастер охоты"},
{"MeleeCharge", "Атака с наскока"},
{"PackRat", "Мастер упаковки"},
{"PathFinder", "Путеводитель"},
{"Poisoner", "Мастер ядов"},
{"QuarterMaster", "Мастер лагерей"},
{"QuickDraw", "Быстрое выхватывание"},
{"Sailor", "Моряк"},
{"Sharpshooter", "Меткий стрелок"},
{"SharpTongue", "Острый язык"},
{"ShieldFighter", "Боец с щитом"},
{"SixthSense", "Шестое чувство"},
{"Smith", "Кузнец"},
{"SpearFighter", "Боец с копьем"},
{"SteadyFeet", "Устойчивые ноги"},
{"SwordFighter", "Боец на мечах"},
{"Tailor", "Портной"},
{"Tanner", "Дубильщик"},
{"Threatening", "Угрожающий"},
{"ThrowingArm", "Наметанная рука"},
{"Wanderer", "Путишественник"},
};
getstr_enum(talent);
assert_enum(talent, Wanderer);

variant	character::getkey(talent_s id) {
	return talent_data[id].type;
}