#include "main.h"

static struct knack_i
{
	const char*			name[2];
} knack_data[] = {
	{{"", ""}},
	//
	{{"Composer", "Композитор"}},
	{{"Drawing", "Рисование"}},
	{{"Musician", "Музыкант"}},
	{{"Sculpting", "Скульптор"}},
	{{"Singing", "Пение"}},
	{{"Writing", "Письмо"}},
	{{"Dancing", "Танцы"}},
	{{"Etiquette", "Этикет"}},
	{{"Fashion", "Стиль"}},
	{{"Oratory", "Ораторство"}},
	{{"Gambling", "Азартные игры"}},
	{{"Quack", "Шарлатанство"}},
	{{"Shadowing", "Слежка"}},
	{{"Stealth", "Скрытность"}},
	{{"Diagnosis", "Диагноз"}},
	{{"First aid", "Первая помощь"}},
	{{"First aid", "Рыбная ловля"}},
	{{"Skinning", "Свеживание"}},
	{{"Survival", "Выживание"}},
	{{"Tracking", "Чтение следов"}},
	{{"Trail signs", "Знание знаков"}},
	{{"Traps", "Ловушки"}},
	{{"Blacksmith", "Кузнец"}},
	{{"Butcher", "Мясник"}},
	{{"Cooking", "Повар"}},
	{{"Fletcher", "Стрельник"}},
	{{"Furrier", "Скорняк"}},
	{{"Innkeeper", "Трактирщик"}},
	{{"Jeweler", "Ювелир"}},
	{{"Miller", "Мельник"}},
	{{"Potter", "Гончар"}},
	{{"Acting", "Игра роли"}},
	{{"Balance", "Равновесие"}},
	{{"Climbing", "Лазание"}},
	{{"Knotwork", "Узлы"}},
	{{"Rigging", "Рангоут"}},
	{{"History", "История"}},
	{{"Mathematics", "Математика"}},
	{{"Philosophy", "Философия"}},
	{{"Research", "Исследования"}},
	{{"Menital task", "Повседневная служба"}},
	{{"Unobrusive", "Незаметность"}},
	{{"Socializing", "Общение"}},
	{{"Street navigation", "Уличная навигация"}},
	{{"Attack (bow)", "Атака (лук)"}},
	{{"Footwork", "Работа ног"}},
	{{"Sprinting", "Ускорение"}},
	{{"Throwing", "Метание"}},
	{{"Parry (buckler)", "Парировать (щит)"}},
	{{"Strategy", "Стратегия"}},
	{{"Tactics", "Тактика"}},
	{{"Attack (сrossbow)", "Атака (арбалет)"}},
	{{"Attack (dirty fighting)", "Атака (грязный бой)"}},
	{{"Attack (fencing)", "Атака (фехтование)"}},
	{{"Parry (fencing)", "Парировать (фехтование)"}},
	{{"Attack (firearms)", "Атака (огнестрельное оружие)"}},
	{{"Attack (heavy weapon)", "Атака (тяжелое оружие)"}},
	{{"Parry (heavy weapon)", "Парировать (тяжелое оружие)"}},
	{{"Attack (knife)", "Атака (нож)"}},
	{{"Parry (knife)", "Парировать (нож)"}},
	{{"Attack (panzerhand)", "Атака (панцерхэнд)"}},
	{{"Parry (panzerhand)", "Парировать (панцерхэнд)"}},
	{{"Attack (polearm)", "Атака (копье)"}},
	{{"Parry (polearm)", "Парировать (копье)"}},
	{{"Attack (pugilism)", "Атака (драка)"}},
	{{"Jab", "Серия ударов"}},
	{{"Ride", "Езда верхом"}},
	{{"Grapple", "Захват"}},
	// Advanced knacks
	{{"Diplomacy", "Дипломатия"}},
	{{"Gaming", "Игры"}},
	{{"Gossip", "Слухи"}},
	{{"Lip reading", "Чтение по губам"}},
	{{"Mooch", "Нахлебничество"}},
	{{"Politics", "Политика"}},
	{{"Scheming", "Интриги"}},
	{{"Sedution", "Соблазнение"}},
	{{"Sincerity", "Искренность"}},
	{{"Ambush", "Засада"}},
	{{"Cheating", "Шулерство"}},
	{{"Lockpicking", "Взлом замков"}},
	{{"Pickpocket", "Карманная кража"}},
	{{"Prestidigitation", "Фокусы"}},
	{{"Scrounging", "Знание свалок"}},
	{{"Dentist", "Дантист"}},
	{{"Examiner", "Обследование"}},
	{{"Surgery", "Хирургия"}},
	{{"Veterinarian", "Ветеринар"}},
	{{"Animal Training", "Дрессировка животных"}},
	{{"Accounting", "Бухгалтерия"}},
	{{"Appraising", "Оценка"}},
	{{"Bartending", "Бармэнство"}},
	{{"Haggling", "Торговаться"}},
	{{"Circus", "Циркач"}},
	{{"Cold Read", "Определение личности"}},
	{{"Disguise", "Подрожание"}},
	{{"Storytelling", "Рассказчик"}},
	{{"Cartography", "Картография"}},
	{{"Leaping", "Прыжки"}},
	{{"Navigation", "Навигация"}},
	{{"Pilot", "Кораблевождение"}},
	{{"Sea lore", "Знание моря"}},
	{{"Swimming", "Плавание"}},
	{{"Weather", "Определение погоды"}},
	{{"Astronomy", "Астрономия"}},
	{{"Law", "Право"}},
	{{"Natural Philosophy", "Натуральная философия"}},
	{{"Occult", "Окультизм"}},
	{{"Theology", "Теология"}},
	{{"Drive сarriage", "Управление каретой"}},
	{{"Seneschal", "Мажордом"}},
	{{"Valet", "Камердинер"}},
	{{"Bribery", "Подкуп"}},
	{{"Conceal", "Умение прятать"}},
	{{"Cryptography", "Шифрование"}},
	{{"Forgery", "Подделка"}},
	{{"Hand Signs", "Язык жестов"}},
	{{"Interrogation", "Допрос"}},
	{{"Poison", "Яд"}},
	{{"Shopping", "Знание магазинов"}},
	{{"Underworld Lore", "Знание дна"}},
	{{"Horse Archery", "Стрельба с коня"}},
	{{"Trick Shooting", "Трюковая стрельба"}},
	{{"Snapshot", "Выстрел навскидку"}},
	{{"Break Fall", "Мягкое падение"}},
	{{"Long-distance Running", "Бег на большую дистанцию"}},
	{{"Lifting", "Поднятие тяжестей"}},
	{{"Rolling", "Перекатывание"}},
	{{"Swinging", "Полет на предмете"}},
	{{"Side-step", "Заход сбоку"}},
	{{"Attack (Buckler)", "Атака (щит)"}},
	{{"Artillery", "Артилерия"}},
	{{"Gunnery", "Пушки"}},
	{{"Incitation", "Воодушивление"}},
	{{"Leadership", "Лидерство"}},
	{{"Logistic", "Логистика"}},
	{{"Reload (Crossbow)", "Перезарядка (арбалет)"}},
	{{"Attack (Improvised Weapon)", "Атака (импровизированное оружие)"}},
	{{"Eye Gouge", "Удар в глаз"}},
	{{"Kick", "Пинок"}},
	{{"Parry (Improvised Weapon)", "Парирование (импровизированное оружие)"}},
	{{"Throat Strike", "Удар в горло"}},
	{{"Throw (Improvised Weapon)", "Метание (импровизированное оружие)"}},
	{{"Reload (Firearms)", "Перезарядка (огнестрельное оружие)"}},
	{{"Throw (Knife)", "Метание (нож)"}},
	{{"Uppercut", "Апперкот"}},
	{{"Set Defence", "Защитная стойка"}},
	{{"Ear Clap", "Хлопок по ушам"}},
	{{"Mounting", "Вскакивание в седло"}},
	{{"Trick Riding", "Трюковая езда"}},
	{{"Bear Hug", "Удушение"}},
	{{"Break", "Ломание костей"}},
	{{"Escape", "Уход от захвата"}},
	{{"Head Butt", "Удар головой"}},
	// Наыки школ фехтования
	{{"Beat", "Мощный удар"}},
	{{"Bind", "Захват оружия"}},
	{{"Corpse-a-Corpse", "Ближний бой"}},
	{{"Disarm", "Обезоруживание"}},
	{{"Double parry", "Двойное парирование"}},
	{{"Feint", "Финт"}},
	{{"Lunge", "Агрессивная атака"}},
	{{"Pommel strike", "Удар эфесом"}},
	{{"Riposte", "Ответный удар"}},
	{{"Togging", "Яркий прием"}},
	{{"Find weakness", "Поиск слабостей"}},
	// Glamour
	{{"The Green Man", "Зеленый человек"}},
	{{"The Honored Hunter", "Рогатый охотник"}},
	{{"Jack", "Джек"}},
	{{"The Robin Good Fellow", "Робин - добрый друг"}},
	{{"Thomas", "Томас"}},
	// Laerdom
	{{"Anger", "Гнев"}},
	{{"Calm", "Спокойствие"}},
	{{"Empathy", "Сопереживание"}},
	{{"Flesh", "Плоть"}},
	{{"Fury", "Ярость"}},
	{{"Gateway", "Врата"}},
	{{"Gloom", "Мрак"}},
	{{"Greatness", "Величие"}},
	{{"Harvest", "Урожай"}},
	{{"Hatred", "Ненависть"}},
	{{"Intensity", "Напряженность"}},
	{{"Journey", "Странствие"}},
	{{"Mountain", "Гора"}},
	{{"Mystery", "Тайна"}},
	{{"Omen", "Знамение"}},
	{{"Passion", "Страсть"}},
	{{"Ruin", "Руины"}},
	{{"Skill", "Умение"}},
	{{"Solitude", "Одиночество"}},
	{{"Strength", "Сила"}},
	{{"Unbound", "Свобода"}},
	{{"Warrior", "Воин"}},
	{{"Wealth", "Богатство"}},
	{{"Wholeness", "Целостность"}},
	// Porte
	{{"Attunement", "Настройка"}},
	{{"Blooding", "Кровавая метка"}},
	{{"Bring", "Притягивание"}},
	{{"Pocket", "Карман"}},
	{{"Walk", "Проход"}},
	// Pyeryem
	{{"Speak", "Разговор"}},
	{{"Man", "Человек"}},
	{{"Cat", "Кот"}},
	{{"Goshawk", "Стервятник"}},
	{{"Bear", "Медведь"}},
	{{"Mouse", "Мышь"}},
	{{"Otter", "Выдра"}},
	{{"Owl", "Сова"}},
	{{"Rabbit", "Кролик"}},
	{{"Fox", "Лиса"}},
	{{"Leopard", "Леопард"}},
	{{"Wolf", "Волк"}},
	// Sorte
	{{"Arcana", "Тайна"}},
	{{"Coins", "Монеты"}},
	{{"Cups", "Чаши"}},
	{{"Staves", "Посохи"}},
	{{"Swords", "Мечи"}},
};
assert_enum(knack, LastSorte);
getstr_enum(knack);