#include "main.h"

static struct magic_power {
	const char*		id;
	const char*		name;
	const char*		visual;
} magic_power_data[] = {
	{"", ""},
	{"Animal Control", "Управления животными"},
	{"Clairaudience", "Яснослышания"},
	{"Clairvoyance", "Ясновидения"},
	{"Climbing", "Лазания"},
	{"Delusion", "Обмана"},
	{"Diminution", "Уменьшения"},
	{"Dragon Control", "Управления драконами"},
	{"Elixir of Health", "Эликсир здоровья"},
	{"Elixir of Madness", "Эликсир сумашествия"},
	{"Elixir of Youth", "Эликсир молодости"},
	{"ESP", "Телепатии"},
	{"Extra Healing", "Экстра лечения"},
	{"Fire Breath", "Огненного дыхания"},
	{"Fire Resistance", "Сопротивления огню"},
	{"Flying", "Полета"},
	{"Gaseous Form", "Газообразной формы"},
	{"Giant Control", "Управления гигантами"},
	{"Giant Strength", "Сила гиганта"},
	{"Growth", "Роста"},
	{"Healing", "Лечения"},
	{"Heroism", "Героизма"},
	{"Human Control", "Управления людьми"},
	{"Invisibility", "Невидимости"},
	{"Invulnerability", "Неуязвимости"},
	{"Levitation", "Левитации"},
	{"Longevity", "Долгожития"},
	{"Acid Resistance", "Сопротивления кислоте"},
	{"Disenchantment", "Разочарования"},
	{"Elemental Invulnerability", "Неузвимости к элементам"},
	{"Etherealness", "Эфирности"},
	{"Fiery Burning", "Адского горения"},
	{"Fumbling", "Неуклюжести"},
	{"Impact", "Удара"},
	{"Slipperiness", "Скользкости"},
	{"Timelessness", ""},
	{"Glibness", ""},
	{"Love", "Любви"},
	{"Persuasiveness", ""},
	{"Stammering and Stuttering", ""},
	{"Plant Control", "Управления растениями"},
	{"Poison", "Яда"},
	{"Polymorph", "Превращения"},
	{"Rainbow Hues", ""},
	{"Speed", "Скорости"},
	{"Super-heroism", ""},
	{"Sweet Water", ""},
	{"Treasure Finding", "Поиска сокровищ"},
	{"Undead Control", "Управление мертвецами"},
	{"Ventriloquism", ""},
	{"Vitality", ""},
	{"Water Breathing", "Дыхания водой"},
	//
	{"Blinking", ""},
	{"Chameleon Power", ""},
	{"Clumsiness", ""},
	{"Contrariness", ""},
	{"Djinni Summoning", ""},
	{"Elemental Command", ""},
	{"Feather Falling", ""},
	{"Free Action", ""},
	{"Jumping", ""},
	{"Mind Shielding", ""},
	{"Protection", "Защиты"},
	{"Ram", ""},
	{"Regeneration", ""},
	{"Shocking Grasp", ""},
	{"Shooting Stars", ""},
	{"Spell Storing", ""},
	{"Spell Turning", ""},
	{"Sustenance", ""},
	{"Swimming", ""},
	{"Telekinesis", ""},
	{"Truth", ""},
	{"Warmth", ""},
	{"Water Walking", ""},
	{"Weakness", ""},
	{"Wizardry", ""},
	{"Darkvision", ""},
	//
	{"Surprise", ""},
};
assert_enum(magic_power, Surprised);
getstr_enum(magic_power);