#include "main.h"

feati bsmeta<feati>::elements[] = {{"No feat", "Нет особенности"},
{"Armor Proficiency (light)", "Ношение легкой брони"},
{"Armor Proficiency (medium)", "Ношение средней брони"},
{"Armor Proficiency (heavy)", "Ношение тяжелой брони"},
{"Shield Proficiency", "Владение щитом"},
{"Simple weapon proficiency", "Владение простым оружием"},
{"Martial weapon proficiency", "Владение смертельным оружием"},
{"Elf weapon training", "Тренировка с оружием эльфов"},
{"Dwarven weapon training", "Тренировка с оружием карликов"},
{"Rogue weapon training", "Тренировка с оружием бродяг"},
//
{"Alchemist Proficiency", "Алхимик"},
{"Calligrapher Proficiency", "Калиграфер"},
{"Carpenter Proficiency", "Плотник"},
{"Cartographer Proficiency", "Картограф"},
{"Cobbler Proficiency", "Башмачник"},
{"Cook Proficiency", "Повар"},
{"Glassblower Proficiency", "Стеклодув"},
{"Jeweler Proficiency", "Ювелир"},
{"Leatherworker Proficiency", "Кожевник"},
{"Mason Proficiency", "Каменьщик"},
{"Painter Proficiency", "Художник"},
{"Potter Proficiency", "Гончар"},
{"Smith Proficiency", "Кузнец"},
{"Tinker Proficiency", "Изобретатель"},
{"Weaver Proficiency", "Ткач"},
{"Woodcarver Proficiency", "Резчик по дереву"},
//
{"Gaming Proficiency", "Игры"},
{"Riding Proficiency", "Езда верхом"},
//
{"Disguise Proficiency", "Изменение внешности"},
{"Forgery Proficiency", "Подделка документов"},
{"Herbalism Proficiency", "Гербализм"},
{"Navigator Proficiency", "Навигация"},
{"Poisoner's tools Proficiency", "Владениями инструментами отравителя"},
{"Theive's tools Proficiency", "Владение воровскими инструментами"},
//
{"Save Strenght", "Спас-бросок по силе"},
{"Save Dexterity", "Спас-бросок по ловкости"},
{"Save Constitution", "Спас-бросок по телосложению"},
{"Save Intellegence", "Спас-бросок по интеллекту"},
{"Save Wisdow", "Спас-бросок по мудросте"},
{"Save Charisma", "Спас-бросок по харизме"},
//
{"Brave", "Храбрость"},
{"Darkvision", "Инфразрение"},
{"Dwarven Resilience", "Выносливость карликов", "Вы получаете преемущество на спас-бросок против яда и сопротивление против повреждений от яда."},
{"Dwarven Toughness", "Живучесть карликов"},
{"Fey Ancestry", "Волшебное происхождение"},
{"Lucky", "Везение"},
{"Mask of the Wild", "Лесная маскировка"},
{"Naturally Stealthy", "Врожденная скрытность"},
{"Stonecunning", "Обработка камня"},
{"Trance", "Транс"},
// Классовые способности воина
{"Second Wind", "Второе дыхание", 0, SecondWindSlot},
{"Action Surge", "Всплеск активности", 0, ActionSurgeSlot},
{"Extra Attack", "Дополнительная атака"},
{"Indomitable", "Несгибаемый", 0, IndomitableSlot},
{"Improved Critical", "Улучшенный критический"},
{"Remarkable Athlete", "Выдающийся атлет"},
{"Superior Critical", "Выдающийся критический"},
{"Survivor", "Крепкий орешек"},
// Классовые способности клерика
{"Spellcasting", "Заклинания"},
{"Channel Divinity", "Касание божества", 0, ChannelDivinitySlot},
{"Destroy Undead", "Уничтожение мертвых"},
{"Divine Intervention", "Божественное чудо"},
{"Disciple of Life", "Учение Жизни"},
{"Blessed Healer", "Священный целитель"},
{"Divine Strike", "Праведный гнев"},
{"Supreme Healing", "Максимальное исцеление"},
// Классовые способности бродяги
{"Sneak Attack", "Подлая атака"},
{"Thieves Cant", "Воровской жаргон"},
{"Cunning Action", "Быстрое действие"},
{"Fast Hands", "Быстрые руки"},
{"Second-story Work", "Стенолаз"},
{"Supreme Sneak", "Невероятная скрытность"},
{"Use Magic Device", "Использование волшебных устройств"},
{"Thiefs Reflexes", "Воровские рефлексы"},
// Стили боя
{"Archery style", "Стиль стрелка", "Получаете бонус +2 к атакующему броску, который вы делаете дистанционным оружием."},
{"Defense style", "Стиль обороны", "Пока вы носите брою получаете +1 к КБ."},
{"Dueling style", "Стиль дуэлянта", "Если вы носите оружие ближнего боя в одной руке и вторая рука остается свободной, получите +2 бонус к броскам урона этого оружия."},
{"Great weapon fighting style", "Стиль двуручного оружия", "Выбросив 1 или 2 при броске урона двуручным оружием, вы можете бросить кубик снова и использовать новый результат, даже если он снова равен 1 или 2. Оружие должно быть двуручным или универсальным, чтобы эта способность действовала на него."},
{"Protection style", "Стиль сражения с щитом", "Если существо, которое вы можете видеть, атакует цель в пределах 5 футов от вас, вы можете среагировать и создать помеху для этой атаки. Для использования этой способности необходим щит."},
{"Two-weapon fighting style", "Стиль сражения двумя оружиями", "Если  вы  сражаетесь  двумя  оружиями,  то  можете  добавить модификатор параметра к урону второй атаки."},
//
{"Expert Athletics", "Эксепрт по атлетике"},
{"Expert Acrobatics", "Эксепрт по акробатике"},
{"Expert Sleight of hands", "Эксепрт по ловкости рук"},
{"Expert Stealth", "Эксепрт по скрытности"},
{"Expert Arcana", "Эксепрт по тайным знаниям"},
{"Expert History", "Эксепрт по истории"},
{"Expert Investigation", "Эксепрт по расследованиям"},
{"Expert Nature", "Эксепрт по природе"},
{"Expert Religion", "Эксепрт по религии"},
{"Expert Animal handling", "Эксепрт по приручению животных"},
{"Expert Insight", "Эксепрт по проницательности"},
{"Expert Medicine", "Эксепрт по медицине"},
{"Expert Perception", "Эксепрт по восприятию"},
{"Expert Survival", "Эксепрт по выживанию"},
{"Expert Deception", "Эксепрт по обману"},
{"Expert Intimidation", "Эксепрт по запугиванию"},
{"Expert Performance", "Эксепрт по артистизму"},
{"Expert Persuasion", "Эксепрт по убеждению"},
//
{"Aggressive", "Агрессивный"},
{"Pack tactics", "Тактика стаи"},
{"Sunlight Sensitivity", "Страдает от солнечного света"},
//
{"Dying", "Умирает"},
{"Guided", "Направлен"},
{"Resisted", "Защищен"},
{"Slowed", "Замедлен"},
};
assert_enum(feat, LastFeat);