#include "main.h"

struct move_info {
	const char*		id;
	const char*		name;
} move_data[] = {
	{"Arcane Art"},
	{"Bardic Lore"},
	{"Charming and Open"},
	{"Port in The Storm", "Убежище во время бури"},
	{"Deity", "Божество"},
	{"Divine guidance", "Святое покровительство"},
	{"Turn Undead", "Отпугнуть мертвых"},
	{"Commune", ""},
	{"Cast a Spell", ""},
	{"Born of The Soil", ""},
	{"By Nature Sustained", ""},
	{"Spirit Tongue", ""},
	{"Shapeshifter", ""},
	{"Studied Essence", ""},
	{"Bend Bars Lift Gates", ""},
	{"Armored", ""},
	{"Signature Weapon", "Именное оружие"},
	{"Lay on Hands", "Возложение рук"},
	{"I am The Law", "Я есть закон"},
	{"Quest", "Миссия"},
	{"Hunt and Track", ""},
	{"Called Shot", ""},
	{"Animal Companion", ""},
	{"Command", ""},
	{"Trap Expert", ""},
	{"Tricks of The Trade", ""},
	{"Backstab", ""},
	{"Flexible Morals", ""},
	{"Poisoner", ""},
	{"Spellbook", ""},
	{"Prepare spells", ""},
	{"Spell defense", ""},
	{"Ritual", ""},
	//
	{"Merciless", ""},
	{"Heirloom", ""},
	{"Improved Weapon", ""},
	{"Seeing Red", ""},
	{"Interrogator", ""},
	{"Scent of Blood", ""},
	{"Iron Hide", ""},
	{"Blacksmith", ""},
	{"Superior Warrior", ""},
	//
	{"Prodigy", ""},
	{"Empowered Magic", ""},
	{"Fount of Knowledge", ""},
	{"Known It All", ""},
	{"Expanded Spellbook", ""},
	{"Enchanter", ""},
	{"Logical", ""},
	{"Arcane Ward", ""},
	{"Counterspell", ""},
	{"Quick Study", ""},
	//
	{"Hack and Slash", ""},
	{"Defy Danger", ""},
	{"Defy Danger", ""},
	{"Defy Danger", ""},
	{"Defy Danger", ""},
	{"Defy Danger", ""},
	{"Defy Danger", ""},
	{"Parley", ""},
	{"Spout Lore", ""},
	{"Discern Realities", ""},
	{"Supply", ""},
	{"Make Camp", ""},
	{"Examine Feature", ""},
	{"Go Back", ""},
	{"Go Next", ""},
	{"Show charsheet sheet", "Изучить листок персонажа"},
};
getstr_enum(move);